# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 066767348481c5869625c111a6a5d489b2b1bf24f030c832cbb814faa6c0bc005653efeb79c594776703aa468884323e6e7e914e929113fb2c95b072738ed24f
  bjc_password: development-bjc-password
  piazza_password: development-piazza-password

test:
  secret_key_base: a3c66cdded70fc6fa14d8aee9446c17c740d812d0b9f0998c7f937a269cba135406087e399eb36ff230fee10befedb7b5eda0eb35dac5c8e4c427039f6c945b7
  bjc_password: test-bjc-password
  piazza_password: test-piazza-password


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bjc_password: <%= ENV["BJC_PASSWORD"] %>
  piazza_password: <%= ENV["PIAZZA_PASSWORD"] %>
