name: All Specs

on: [push, pull_request]

jobs:
  specs:
    name: Tests
    runs-on: ubuntu-latest
    continue-on-error: true
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    strategy:
      fail-fast: false
      matrix:
        suite:
          - cucumber
          - rspec
    env:
      TZ: America/Los_Angeles
      RAILS_ENV: test
      RUBY_ENV: test
      attr_encrypted_key: '12345678912345678912345678912345'
      DISPLAY: ':99' # For chromedriver
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Use Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - run: bin/yarn
      - run: bin/rails webpacker:compile
      - run: bundle exec rake db:setup
      - run: bundle exec rake db:migrate
      - run: bundle exec ${{ matrix.suite }}
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
